# Generated by Django 5.2.3 on 2025-06-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_newspost_title_newspostimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspost",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
