# Generated by Django 5.2.3 on 2025-06-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_newspost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='category',
            field=models.CharField(choices=[('nepal', 'Nepal Cricket'), ('associate', 'Associate Cricket'), ('icc', 'ICC Events'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
